window.TalentFlowData = {
  company: {
    name: "JAMS",
    workspace: "Northstar Hiring",
    activeRole: "Recruiter",
    user: "Ananya Rao",
  },
  metrics: [
    {
      label: "Active openings",
      value: "18",
      trend: "+4 this month",
      tone: "blue",
      icon: "briefcase",
    },
    {
      label: "Candidates in pipeline",
      value: "247",
      trend: "+32 new profiles",
      tone: "green",
      icon: "users",
    },
    {
      label: "Interviews scheduled",
      value: "41",
      trend: "12 this week",
      tone: "amber",
      icon: "calendar",
    },
    {
      label: "Avg. time to hire",
      value: "21d",
      trend: "-5d improved",
      tone: "rose",
      icon: "chart",
    },
  ],
  jobs: [
    {
      id: "JOB-1428",
      title: "Senior Frontend Engineer",
      department: "Product Engineering",
      location: "Bengaluru / Remote",
      applicants: 64,
      status: "Published",
      owner: "Meera Iyer",
      priority: "High",
    },
    {
      id: "JOB-1397",
      title: "Growth Marketing Manager",
      department: "Revenue",
      location: "Mumbai",
      applicants: 38,
      status: "Screening",
      owner: "Rahul Menon",
      priority: "Medium",
    },
    {
      id: "JOB-1362",
      title: "People Operations Lead",
      department: "HR",
      location: "Hyderabad",
      applicants: 29,
      status: "Interviewing",
      owner: "Ananya Rao",
      priority: "Medium",
    },
  ],
  companies: [
    {
      name: "NovaWorks",
      industry: "SaaS",
      location: "Bengaluru",
      roles: 8,
      hiringFor: "Frontend, QA, DevOps",
      rating: "4.6",
      color: "blue",
    },
    {
      name: "FinEdge Labs",
      industry: "FinTech",
      location: "Mumbai",
      roles: 5,
      hiringFor: "Backend, Data, Security",
      rating: "4.4",
      color: "green",
    },
    {
      name: "CloudNest",
      industry: "Cloud Infrastructure",
      location: "Hyderabad",
      roles: 6,
      hiringFor: "DevOps, SRE, Support",
      rating: "4.7",
      color: "violet",
    },
    {
      name: "MarketPulse",
      industry: "Marketing Tech",
      location: "Remote",
      roles: 4,
      hiringFor: "Growth, Design, Sales",
      rating: "4.3",
      color: "rose",
    },
  ],
  opportunities: [
    {
      company: "NovaWorks",
      title: "React Developer",
      location: "Bengaluru",
      type: "Hybrid",
      salary: "12-18 LPA",
      match: 93,
      tags: ["React", "TypeScript", "Design Systems"],
    },
    {
      company: "FinEdge Labs",
      title: "Node.js Engineer",
      location: "Mumbai",
      type: "On-site",
      salary: "10-16 LPA",
      match: 88,
      tags: ["Node.js", "MongoDB", "JWT"],
    },
    {
      company: "CloudNest",
      title: "DevOps Associate",
      location: "Hyderabad",
      type: "Hybrid",
      salary: "9-14 LPA",
      match: 84,
      tags: ["AWS", "Docker", "CI/CD"],
    },
    {
      company: "MarketPulse",
      title: "Product Designer",
      location: "Remote",
      type: "Remote",
      salary: "8-13 LPA",
      match: 81,
      tags: ["Figma", "Research", "Prototyping"],
    },
  ],
  candidateProfiles: [
    {
      name: "Devika Sharma",
      headline: "Frontend Engineer",
      location: "Bengaluru",
      status: "Open to interview",
      completeness: 92,
      connections: 18,
      color: "blue",
    },
    {
      name: "Arjun Patel",
      headline: "Backend Engineer",
      location: "Mumbai",
      status: "Actively applying",
      completeness: 86,
      connections: 12,
      color: "green",
    },
    {
      name: "Nisha Thomas",
      headline: "Product Designer",
      location: "Remote",
      status: "Portfolio ready",
      completeness: 89,
      connections: 25,
      color: "violet",
    },
  ],
  resumeDesigner: {
    templates: ["Classic ATS", "Modern Product", "Compact Fresher"],
    sections: ["Summary", "Skills", "Experience", "Projects", "Education", "Certifications"],
    score: 84,
    suggestions: [
      "Add measurable impact to your latest project.",
      "Move strongest skills into the first section.",
      "Keep resume under two pages for ATS screening.",
    ],
  },
  filters: {
    roles: ["Frontend", "Backend", "Design", "DevOps", "Data"],
    locations: ["Bengaluru", "Mumbai", "Hyderabad", "Remote"],
    workModes: ["Remote", "Hybrid", "On-site"],
  },
  stages: [
    {
      name: "Applied",
      count: 88,
      candidates: [
        {
          name: "Devika Sharma",
          role: "Frontend Engineer",
          score: 92,
          source: "LinkedIn",
          skills: ["React", "TypeScript", "Design Systems"],
        },
        {
          name: "Arjun Patel",
          role: "Backend Engineer",
          score: 86,
          source: "Referral",
          skills: ["Node.js", "MongoDB", "APIs"],
        },
      ],
    },
    {
      name: "Interview",
      count: 51,
      candidates: [
        {
          name: "Nisha Thomas",
          role: "Product Designer",
          score: 89,
          source: "Careers page",
          skills: ["Research", "Figma", "Prototyping"],
        },
        {
          name: "Kabir Khan",
          role: "Data Analyst",
          score: 84,
          source: "Indeed",
          skills: ["SQL", "Dashboards", "Cohorts"],
        },
      ],
    },
    {
      name: "Offer",
      count: 17,
      candidates: [
        {
          name: "Sahana Reddy",
          role: "QA Automation",
          score: 94,
          source: "Referral",
          skills: ["Cypress", "API Testing", "CI"],
        },
      ],
    },
    {
      name: "Hired",
      count: 12,
      candidates: [
        {
          name: "Vikram Sethi",
          role: "DevOps Engineer",
          score: 91,
          source: "AngelList",
          skills: ["AWS", "Docker", "Monitoring"],
        },
      ],
    },
  ],
  interviews: [
    {
      time: "10:00",
      candidate: "Nisha Thomas",
      type: "Portfolio review",
      panel: "Design + Hiring Manager",
      status: "Confirmed",
    },
    {
      time: "12:30",
      candidate: "Devika Sharma",
      type: "Technical round",
      panel: "Frontend Guild",
      status: "Calendar synced",
    },
    {
      time: "16:00",
      candidate: "Kabir Khan",
      type: "Case discussion",
      panel: "Analytics Team",
      status: "Feedback due",
    },
  ],
  feedback: [
    {
      interviewer: "Rohan Das",
      candidate: "Sahana Reddy",
      verdict: "Strong hire",
      note: "Excellent automation depth and clear ownership examples.",
    },
    {
      interviewer: "Priya Nair",
      candidate: "Devika Sharma",
      verdict: "Move forward",
      note: "Strong React fundamentals, wants more system design exposure.",
    },
  ],
  analytics: [
    { label: "Source quality", value: 78 },
    { label: "Offer acceptance", value: 64 },
    { label: "Pipeline health", value: 83 },
    { label: "Feedback SLA", value: 71 },
  ],
  sources: [
    { name: "LinkedIn", candidates: 96, quality: 82, color: "blue" },
    { name: "Referrals", candidates: 54, quality: 91, color: "green" },
    { name: "Careers page", candidates: 43, quality: 73, color: "amber" },
    { name: "Indeed", candidates: 31, quality: 68, color: "rose" },
  ],
  workflowSteps: [
    {
      name: "Post",
      icon: "briefcase",
      color: "blue",
      title: "Publish everywhere",
      detail: "Push one job to job boards, the branded careers page, and referral channels.",
    },
    {
      name: "Parse",
      icon: "users",
      color: "green",
      title: "Build profiles",
      detail: "Extract skills, education, experience, contact details, and fit signals from resumes.",
    },
    {
      name: "Screen",
      icon: "chart",
      color: "violet",
      title: "Rank with context",
      detail: "Use match score, requirement checklist, anonymized review, and source quality.",
    },
    {
      name: "Schedule",
      icon: "calendar",
      color: "amber",
      title: "Book faster",
      detail: "Coordinate panels, time slots, interview kits, and Google or Outlook calendar sync.",
    },
    {
      name: "Decide",
      icon: "chart",
      color: "rose",
      title: "Collect scorecards",
      detail: "Standardize feedback with focus attributes, recommendations, and hiring manager notes.",
    },
    {
      name: "Offer",
      icon: "briefcase",
      color: "teal",
      title: "Close the loop",
      detail: "Manage approvals, offer status, candidate portal updates, and onboarding handoff.",
    },
  ],
  atsOptions: [
    { name: "Job board blast", detail: "200+ board style distribution", color: "blue", badge: "Sourcing" },
    { name: "Careers page builder", detail: "Branded public job portal", color: "green", badge: "Brand" },
    { name: "Talent CRM", detail: "Searchable candidate database", color: "violet", badge: "Pipeline" },
    { name: "Interview kits", detail: "Questions, resume, scorecard", color: "amber", badge: "Structured" },
    { name: "One-way video", detail: "Async screening round", color: "rose", badge: "Assess" },
    { name: "Offer approvals", detail: "Templates and e-signature ready", color: "teal", badge: "Hiring" },
    { name: "SLA alerts", detail: "Stage aging reminders", color: "orange", badge: "Automation" },
    { name: "Dashboard filters", detail: "Slice by job, source, role, stage", color: "blue", badge: "Analytics" },
  ],
  alerts: [
    { label: "5 candidates stuck in Interview", action: "Review stage aging", color: "rose" },
    { label: "2 scorecards due before 6 PM", action: "Nudge panel", color: "amber" },
    { label: "Frontend Engineer offer at risk", action: "Open approval", color: "blue" },
  ],
  botTips: [
    "I can shortlist candidates with high match scores.",
    "Try the hover workflow to see the hiring steps.",
    "You have 2 scorecards due today.",
    "Post a job, parse resumes, schedule interviews, collect scorecards, then release offers.",
  ],
  hiringHealth: [
    { label: "Screening SLA", value: "92%", detail: "Most candidates reviewed within 24h" },
    { label: "Stale profiles", value: "11", detail: "Need recruiter follow-up today" },
    { label: "Offer risk", value: "3", detail: "Compensation alignment pending" },
  ],
  notifications: [
    { title: "Calendar conflict resolved", detail: "Devika's technical round moved to 12:30", tone: "blue" },
    { title: "Feedback reminder sent", detail: "Priya Nair has 2 pending scorecards", tone: "amber" },
    { title: "Candidate portal updated", detail: "Offer status visible to Sahana Reddy", tone: "green" },
  ],
  parsedResume: {
    file: "devika-sharma-resume.pdf",
    match: 92,
    fields: [
      { label: "Skills", value: "React, TypeScript, Design Systems, REST APIs" },
      { label: "Experience", value: "5 years / SaaS product teams" },
      { label: "Education", value: "B.Tech Computer Science" },
      { label: "Recommended stage", value: "Technical interview" },
    ],
  },
  services: [
    { name: "Auth", detail: "JWT, bcrypt, role access", tone: "rose" },
    { name: "Jobs", detail: "Openings, publishing, ownership", tone: "amber" },
    { name: "Candidates", detail: "Profiles, resumes, parsed data", tone: "green" },
    { name: "Pipeline", detail: "Applied, Interview, Offer, Hired", tone: "orange" },
    { name: "Interview", detail: "Calendar sync and feedback", tone: "blue" },
    { name: "Analytics", detail: "Reports and hiring metrics", tone: "teal" },
  ],
  collections: ["Users", "Jobs", "Candidates", "Interviews", "Feedback", "Reports"],
  activity: [
    "Resume parsed for Devika Sharma with 14 extracted skills",
    "Interview scheduled for Kabir Khan via Google Calendar",
    "Hiring manager feedback submitted for Sahana Reddy",
    "Senior Frontend Engineer moved to high priority",
  ],
};
