export const dashboardData = {
  metrics: [
    { label: "Active openings", value: "18", trend: "+4 this month" },
    { label: "Candidates in pipeline", value: "247", trend: "+32 new profiles" },
    { label: "Interviews scheduled", value: "41", trend: "12 this week" },
    { label: "Avg. time to hire", value: "21d", trend: "-5 days improved" },
  ],
  stages: [
    { name: "Applied", count: 88 },
    { name: "Screening", count: 41 },
    { name: "Interview", count: 29 },
    { name: "Offer", count: 11 },
    { name: "Hired", count: 7 },
  ],
  jobs: [
    {
      id: "job-1",
      title: "Frontend",
      department: "Product Engineering",
      location: "Bengaluru / Remote",
      applicants: 142,
      status: "Published",
      approvalStatus: "Approved",
      openings: 2,
      hiringManager: "Rohan Mehta",
      stages: ["Applied", "Screening", "Interview", "Offer", "Hired"],
      skills: ["React", "TypeScript", "Design Systems"],
    },
    {
      id: "job-2",
      title: "Designer",
      department: "Revenue",
      location: "Mumbai",
      applicants: 89,
      status: "Screening",
      approvalStatus: "Pending",
      openings: 1,
      hiringManager: "Asha Menon",
      stages: ["Applied", "Screening", "Interview", "Offer", "Hired"],
      skills: ["Lifecycle", "Campaigns", "Analytics"],
    },
    {
      id: "job-3",
      title: "Backend",
      department: "Engineering",
      location: "Hyderabad",
      applicants: 64,
      status: "Interviewing",
      approvalStatus: "Approved",
      openings: 1,
      hiringManager: "Vikram Das",
      stages: ["Applied", "Screening", "Interview", "Offer", "Hired"],
      skills: ["Node.js", "MongoDB", "AWS"],
    },
  ],
  candidates: [
    {
      id: "cand-1",
      name: "Devika Sharma",
      role: "Frontend Engineer",
      score: 92,
      stage: "Screening",
      source: "LinkedIn",
      location: "Bengaluru",
      experience: "5 years",
      skills: ["React", "TypeScript", "Accessibility"],
      tags: ["Shortlisted", "Follow-up"],
      note: "Strong UI systems experience. Needs final architecture round.",
    },
    {
      id: "cand-2",
      name: "Arjun Patel",
      role: "Backend Engineer",
      score: 86,
      stage: "Applied",
      source: "Referral",
      location: "Pune",
      experience: "4 years",
      skills: ["Node.js", "MongoDB", "AWS"],
      tags: ["New", "Auto-parsed"],
      note: "Good infra background. Recruiter to schedule screening.",
    },
    {
      id: "cand-3",
      name: "Nisha Thomas",
      role: "Product Designer",
      score: 89,
      stage: "Interview",
      source: "Careers page",
      location: "Remote",
      experience: "6 years",
      skills: ["Figma", "Research", "Design Systems"],
      tags: ["Interview", "Manager review"],
      note: "Portfolio review pending hiring manager feedback.",
    },
    {
      id: "cand-4",
      name: "Sahana Reddy",
      role: "QA Automation",
      score: 94,
      stage: "Offer",
      source: "Referral",
      location: "Hyderabad",
      experience: "7 years",
      skills: ["Playwright", "Cypress", "CI"],
      tags: ["Offer", "Priority"],
      note: "Compensation discussion in progress.",
    },
  ],
  applications: [
    {
      id: "app-1",
      jobTitle: "Senior Frontend Engineer",
      company: "JAMS",
      status: "Interview",
      updatedAt: "Updated 2 hours ago",
    },
    {
      id: "app-2",
      jobTitle: "Product Designer",
      company: "JAMS",
      status: "Applied",
      updatedAt: "Updated yesterday",
    },
    {
      id: "app-3",
      jobTitle: "Growth Marketing Manager",
      company: "JAMS",
      status: "Rejected",
      updatedAt: "Updated 3 days ago",
    },
  ],
  interviewSchedule: [
    {
      id: "int-1",
      time: "10:00 AM",
      candidate: "Nisha Thomas",
      detail: "Portfolio review with hiring manager",
      status: "Confirmed",
    },
    {
      id: "int-2",
      time: "12:30 PM",
      candidate: "Devika Sharma",
      detail: "Technical round with panel",
      status: "Feedback due",
    },
    {
      id: "int-3",
      time: "4:00 PM",
      candidate: "Sahana Reddy",
      detail: "Final discussion and offer alignment",
      status: "Scheduled",
    },
  ],
  managerQueue: [
    {
      id: "mgr-1",
      title: "Approve new requisition",
      detail: "Growth Marketing Manager requires budget approval before publish.",
    },
    {
      id: "mgr-2",
      title: "Review shortlisted profile",
      detail: "Nisha Thomas needs final design review and structured feedback.",
    },
    {
      id: "mgr-3",
      title: "Decision pending",
      detail: "Sahana Reddy offer approval is waiting on compensation sign-off.",
    },
  ],
  notifications: [
    "Application received mail sent to 12 candidates.",
    "2 interview reminders scheduled for tomorrow morning.",
    "1 duplicate candidate profile prevented during resume upload.",
  ],
};
